/**
 * @file pinmux_config.h
 * @brief
 *
 * Copyright (c) 2021 Bouffalolab team
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 */
#ifndef _PINMUX_CONFIG_H
#define _PINMUX_CONFIG_H

#if 0
// <<< Use Configuration Wizard in Context Menu >>>

// <q> GPIO0 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio0 function GPIO0, MISO/MOSI,SCL,I2S_BCLK,PWM_CH0  JTAG_TMS
#define CONFIG_GPIO0_FUNC GPIO_FUN_UNUSED // GPIO_FUN_E21_JTAG

// <q> GPIO1 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_UART0_CTS//GPIO_FUN_UART1_CTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio1 function GPIO1, MISO/MOSI,SDA,I2S_FS,PWM_CH1 JTAG_TDI
#define CONFIG_GPIO1_FUNC GPIO_FUN_UNUSED // GPIO_FUN_E21_JTAG

// <q> GPIO2 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_UART0_TX//GPIO_FUN_UART1_TX//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio2 function GPIO2, MISO/MOSI,SCL,I2S_DIO,PWM_CH2  JTAG_TCK
#define CONFIG_GPIO2_FUNC GPIO_FUN_UART1_TX // GPIO_FUN_UNUSED

// <q> GPIO7 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RX//GPIO_FUN_UART1_RX//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio7 function DM/USB_DP,SCLK,SDA,PWM_CH2,ADC_CH6 
#define CONFIG_GPIO7_FUNC GPIO_FUN_USB

// <q> GPIO8 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio8 function DP/USB_DM, MISO/MOSI,SCL,PWM_CH3,ADC_CH0 
#define CONFIG_GPIO8_FUNC GPIO_FUN_USB

// <q> GPIO9 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio9 function GPIO9, MISO/MOSI,SDA,I2S_FS,PWM_CH4,ADC_CH7 JTAG_TDO
#define CONFIG_GPIO9_FUNC GPIO_FUN_ADC // GPIO_FUN_E21_JTAG // GPIO_FUN_UNUSED

// Only test!!!
//#define CONFIG_GPIO11_FUNC GPIO_FUN_DAC
// Only test!!!
//#define CONFIG_GPIO12_FUNC GPIO_FUN_ADC

// <q> GPIO14 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio14 function UART0_TX/GPIO14,SS,SCL,ADC_CH5,I2S_DIO,PWM_CH4 
#define CONFIG_GPIO14_FUNC GPIO_FUN_UART0_TX

// <q> GPIO15 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio15 function UART0_RX/JTAG_TCK/GPIO15,SCLK,SDA,ADC_CH1,I2S_DIO,PWM_CH0
#define CONFIG_GPIO15_FUNC GPIO_FUN_UART0_RX 

// <q> GPIO17 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio17 function GPIO17,MISO/MOSI,SDA,I2S_FS,PWM_CH2,DAC 
#define CONFIG_GPIO17_FUNC GPIO_FUN_DAC // GPIO_FUN_UNUSED

// <q> GPIO23 Not in DevKit! Only Module!
// <i> config gpio23 function GPIO23, SCLK, I2S_DI, SPI,SDA,PWM_CH3,IRTX
#define CONFIG_GPIO23_FUNC GPIO_FUN_UNUSED

// <q> GPIO24 Not in Module!
// <i> config gpio24 function GPIO24
//#define CONFIG_GPIO24_FUNC GPIO_FUN_UNUSED

// <q> GPIO25
// <i> config gpio25 function GPIO25,MISO/MOSI,SDA,I2S_FS,PWM_CH0
#define CONFIG_GPIO25_FUNC GPIO_FUN_UNUSED

// <q> GPIO26 Not in Module!
// <i> config gpio26 function GPIO26
//#define CONFIG_GPIO26_FUNC GPIO_FUN_UNUSED

// <q> GPIO27
// <i> config gpio27 function GPIO27
#define CONFIG_GPIO27_FUNC GPIO_FUN_UART1_RX

// <q> GPIO28 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio28 function (BOOT)/GPIO28,MISO/MOSI,SCL,I2S_BCLK,PWM_CH3 
#define CONFIG_GPIO28_FUNC GPIO_FUN_UNUSED


#else

// <q> GPIO0 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio0 function GPIO0, MISO/MOSI,SCL,I2S_BCLK,PWM_CH0  JTAG_TMS
#define CONFIG_GPIO0_FUNC GPIO_FUN_E21_JTAG // GPIO_FUN_UNUSED

// <q> GPIO1 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_UART0_CTS//GPIO_FUN_UART1_CTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio1 function GPIO1, MISO/MOSI,SDA,I2S_FS,PWM_CH1 JTAG_TDI
#define CONFIG_GPIO1_FUNC GPIO_FUN_E21_JTAG // GPIO_FUN_UNUSED

// <q> GPIO2 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_UART0_TX//GPIO_FUN_UART1_TX//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio2 function GPIO2, MISO/MOSI,SCL,I2S_DIO,PWM_CH2  JTAG_TCK
#define CONFIG_GPIO2_FUNC GPIO_FUN_E21_JTAG // GPIO_FUN_UART1_TX // GPIO_FUN_UNUSED

// <q> GPIO7 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RX//GPIO_FUN_UART1_RX//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio7 function DM/USB_DP,SCLK,SDA,PWM_CH2,ADC_CH6 
#define CONFIG_GPIO7_FUNC GPIO_FUN_USB

// <q> GPIO8 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio8 function DP/USB_DM, MISO/MOSI,SCL,PWM_CH3,ADC_CH0 
#define CONFIG_GPIO8_FUNC GPIO_FUN_USB

// <q> GPIO9 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio9 function GPIO9, MISO/MOSI,SDA,I2S_FS,PWM_CH4,ADC_CH7 JTAG_TDO
#define CONFIG_GPIO9_FUNC GPIO_FUN_ADC // GPIO_FUN_E21_JTAG // GPIO_FUN_ADC // GPIO_FUN_UNUSED

// Only test!!!
#define CONFIG_GPIO11_FUNC GPIO_FUN_DAC
// Only test!!!

// <q> GPIO14 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio14 function UART0_TX/GPIO14,SS,SCL,ADC_CH5,I2S_DIO,PWM_CH4 
#define CONFIG_GPIO14_FUNC GPIO_FUN_UART0_TX

// <q> GPIO15 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio15 function UART0_RX/JTAG_TCK/GPIO15,SCLK,SDA,ADC_CH1,I2S_DIO,PWM_CH0 JTAG_TDO/TDI
#define CONFIG_GPIO15_FUNC GPIO_FUN_UART0_RX 

// <q> GPIO17 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio17 function GPIO17,MISO/MOSI,SDA,I2S_FS,PWM_CH2,DAC 
#define CONFIG_GPIO17_FUNC GPIO_FUN_DAC

// <q> GPIO23 DevKit None! Only Module!
// <i> config gpio23 function GPIO23, SCLK, I2S_DI, SPI,SDA,PWM_CH3,IRTX JTAG_TDO/TDI
#define CONFIG_GPIO23_FUNC GPIO_FUN_UNUSED

// <q> GPIO24 Not in Module!
// <i> config gpio24 function GPIO24
//#define CONFIG_GPIO24_FUNC GPIO_FUN_UNUSED

// <q> GPIO25
// <i> config gpio25 function GPIO25,MISO/MOSI,SDA,I2S_FS,PWM_CH0
#define CONFIG_GPIO25_FUNC GPIO_FUN_UNUSED // GPIO_FUN_UART1_TX

// <q> GPIO26 Not in Module!
// <i> config gpio26 function GPIO26
//#define CONFIG_GPIO26_FUNC GPIO_FUN_UNUSED

// <q> GPIO27
// <i> config gpio27 function GPIO27
#define CONFIG_GPIO27_FUNC  GPIO_FUN_UNUSED // GPIO_FUN_UART1_RX

// <q> GPIO28 <2> [GPIO_FUN_UNUSED//GPIO_FUN_I2S//GPIO_FUN_SPI//GPIO_FUN_I2C//GPIO_FUN_PWM//GPIO_FUN_CAM//GPIO_FUN_USB//GPIO_FUN_UART0_RTS//GPIO_FUN_UART1_RTS//GPIO_FUN_ETHER_MAC//GPIO_FUN_QDEC]
// <i> config gpio28 function (BOOT)/GPIO28,MISO/MOSI,SCL,I2S_BCLK,PWM_CH3 
#define CONFIG_GPIO28_FUNC GPIO_FUN_UNUSED

#endif

#endif
